baseURL = 'https://george-cliff.github.io/'
languageCode = 'en-gb'
title = 'George Cliff'
theme = 'PaperMod'

[params]
description = "CS student building projects"
ShowReadingTime = true
ShowPostNavLinks = true

[menu]
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2


[[params.socialIcons]]
name = "mastodon"
url = "https://mastodon.social/@gcliff"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/george-cliff-b94127187/"
